Fix error due to: 503 bad command sequence
503 bad command sequence was creating an unhandled error. 
This fixed it for me but I don't pretend to think this is the right solution.


SERVER 1:
└──503 Bad command sequence

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: Data command failed - 503 Bad command sequence
    at SMTPClient._actionDATA (/home/jpx/mailapp/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:806:23)
    at SMTPClient._onData (/home/jpx/mailapp/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:252:29)
    at Socket.EventEmitter.emit (events.js:88:17)
    at TCP.onread (net.js:395:14)